---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: mup-namespace
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      location / {
        default_type application/json;
        return 200 '{"message":"Hello from Kubernetes"}';
      }
    }
