---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: mup-namespace
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d/default.conf
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
